### ISSUE TITLE
where put dns

### ISSUE THREAD

**Issue by mateo24xx** [r00t-3xp10it/venom#19]
i have just a question "is it possible to write dns adress in LHOST ? "
![1](https://user-images.githubusercontent.com/24534204/36698231-9f7d78da-1b49-11e8-8bb5-e9fc6b6789d1.PNG)

**Comment by r00t-3xp10it** [comment]
well i dont know if **office_ms17_11882.rb** accepts Domain names or dns adresses in RHOST variable, because reading the module i can see that the only option to set its **FILENAME** ..
![1](http://i.cubeupload.com/JGYYGq.png)

Also the module uses metasploit **HttpServer** to deliver the .rtf exploit to target
![1](http://i.cubeupload.com/yvqcor.png)


the msf module:
https://github.com/r00t-3xp10it/venom/blob/master/aux/msf/office_ms17_11882.rb
