### ISSUE TITLE
{xterm} not found

### ISSUE THREAD

**Issue by mtanmoy798** [r00t-3xp10it/venom#34]
./venom.sh: 7221: ./venom.sh: xterm: not found

help me to solve it

**Comment by r00t-3xp10it** [comment]
uau ... amazing .. are you using a **linux** system ???
because **xterm** its installed by default i belive ..

xterm: https://invisible-island.net/xterm/

**Comment by mtanmoy798** [comment]
Im using ubantu

**Comment by r00t-3xp10it** [comment]
i have used ubuntu long time ago..
and xterm its native at the time i've used ubuntu distro,
for some reason it seems that xterm its no longer native.. so..install it ..

how to install xterm on ubuntu: http://zoomadmin.com/HowToInstall/UbuntuPackage/xterm

**Comment by mtanmoy798** [comment]
Thanks.
By the way ,how it will be for hacking..if i use kali

**Comment by r00t-3xp10it** [comment]
well .. **kali** its nothing more that a linux distro with the best hacking tools installed by default..
we can use any linux distro to pentesting (hacking) but we need first to install all tools manually before start using them ... thats one of the reasons why people use **kali** for pentesting..

because we dont need to install hacking tool manually ..

**Comment by mtanmoy798** [comment]
Yes i have installed metaspliot framework
...
Xan i get your email or Whatsapp app..or phone number anything

**Comment by r00t-3xp10it** [comment]
facebook: Pedro Ubuntu Nobrega

![facebook](http://i63.tinypic.com/fx87z6.png)

**Comment by dwiindr47** [comment]
i have peoblem finish paylond Apk, any problem  like this 
cannot stat '/root/.msf4/local
