### ISSUE TITLE
windows agent 3 not working

### ISSUE THREAD

**Issue by usama7628674** [r00t-3xp10it/venom#36]
@r00t-3xp10it Not getting meterpreter shell
Windows payload with agent 3 PY(Pyherion/NXcrypt)
Tested on windows 10 v1809 and v1903
Used pyinstaller for compilation,didn't use pyherion and nxcrypt.

**Comment by r00t-3xp10it** [comment]
iam current working in venom ### 1.0.16 version ..
many of venom payloads are now beeing caugth by AV soluctions ..
(so fix that **pyinstaller** error in your distro does not matter now)..

venom V:1.0.16 will present 4 new **evasion payloads** <-- play with this ones insted ..
(release date preview: agost)

**Comment by usama7628674** [comment]
Don't worry I can make them FUD

**Comment by usama7628674** [comment]
@r00t-3xp10it I'm getting the following error if I run .py file (not converted to .exe)
```
Traceback (most recent call last):
  File "shellcode.py", line 19, in <module>
    iKaiRSdDk()
WindowsError: exception: access violation writing 0x02FA9CE8
```

**Comment by r00t-3xp10it** [comment]
yes ...maybee.. i have now finished all pending projects ..
i can now return to venom v:1.0.16 release ..

**Comment by usama7628674** [comment]
@r00t-3xp10it Sounds good.

**Comment by r00t-3xp10it** [comment]
**Question:**
Did you have copy the shellcode from venom terminal windows to exec.py file and then saved the file?
![bug1](https://user-images.githubusercontent.com/23490060/71022585-b5a9be00-20f8-11ea-887b-ce1a11d8b56c.png)
because i have reproduced your steps:
**Used pyinstaller for compilation,didn't use pyherion and nxcrypt.**
![bug2](https://user-images.githubusercontent.com/23490060/71022943-9bbcab00-20f9-11ea-99e9-34a5c97a76e3.png)
And i have try to run it againts my windows 7 (**inside wine**)
and the payload have successfully connected back..
![bug3](https://user-images.githubusercontent.com/23490060/71023038-d1fa2a80-20f9-11ea-8afd-434260de19c3.png)

**Comment by usama7628674** [comment]
@r00t-3xp10it Hmmm let me check again and we'll continue discussion later then.

**Comment by kl0101** [comment]
@r00t-3xp10it I have exactly the same unsolved problem, the payload does not work.

**Comment by r00t-3xp10it** [comment]
Did you have copy the **shellcode** from venom terminal to **exec.py** file and then saved the file?
![bug1](https://user-images.githubusercontent.com/23490060/71022585-b5a9be00-20f8-11ea-887b-ce1a11d8b56c.png)

Does your **wine** its configurated to use the same target arch ?? 
example: if your target its windows10 then set wine to windows10 ..
