### ISSUE TITLE
x64-Resize: Time out occurred?

### ISSUE THREAD

**Issue by codings9** [r00t-3xp10it/venom#41]
This seems to happen on:
Linux kali 5.3.0-kali2-amd64 #1 SMP Debian 5.3.9-3kali1 (2019-11-20) x86_64 GNU/Linux, why?
![5EDA1B39-937A-47A8-BB52-D4970EED7E12](https://user-images.githubusercontent.com/6113072/71395429-be076a80-25ca-11ea-887f-e32796ea1f1d.jpeg)

**Comment by r00t-3xp10it** [comment]
[resize](https://linux.die.net/man/1/resize)

its the first time i hear of resize (bash native) giving this error ..
1) are you using default bash (sh) shell ??? ( i bet you are using another bash shell)

## Quick Fix
![bug](https://user-images.githubusercontent.com/23490060/71425535-050e6200-2696-11ea-8103-1e1bce605a0c.png)

**Comment by codings9** [comment]
Xterm or Bash same thing, downloaded the latest git, same, just be aware this works on 32bit or i686, but not x64.
![299F8DB0-D271-41B3-9042-CCB70170D30C](https://user-images.githubusercontent.com/6113072/71426674-f908ad00-2661-11ea-810f-47c0e1db5321.jpeg)
![FA88DA27-347F-4844-83A0-58DC1EC8CFD4](https://user-images.githubusercontent.com/6113072/71426676-ff972480-2661-11ea-824f-395db19b3c11.jpeg)

**Comment by r00t-3xp10it** [comment]
I should not be wasting my time with you, just for your response ..
but today iam in a good mood, so here it goes: 

### 1º look at the instructions that i have given you
The are **2** screenshots ...
- one says: delete the resize command from **>>>venom.sh<<<**
- the other says: delete the resize command from **>>>setup.sh<<<**
- Does your distro have **zenity** dependencie (packet) installed ????
  because that `[*] Script Execution Aborted ..` normaly happens when users
  forget to install **zenity** dependencie <-- ALL my bash tool require zenity GUI's
  to capture user inputs ....

    - check if you have zenity installed `zenity --version`
    - install zenity `sudo apt-get install zenity`
    - zenity homepage: https://help.gnome.org/users/zenity/

In version 1.0.15 release **@usama7628674** have help my config setup.sh to work in x64 bites:
https://github.com/r00t-3xp10it/venom/issues/22#issuecomment-381007778 Next time i will not respond you, since you dont know how to be polite ..and then you are going to be convinced that
venom does not work in x64 and we all be happy ..

**Comment by codings9** [comment]
Thank you-Solved, thank you:
How?
check if you have zenity installed zenity --version
install zenity sudo apt-get install zenity

**Comment by codings9** [comment]
> I should not be wasting my time with you, just for your response ..
> but today iam in a good mood, so here it goes:
> 
> ### 1º look at the instructions that i have given you
> The are **2** screenshots ...
> 
> * one says: delete the resize command from **>>>venom.sh<<<**
> * the other says: delete the resize command from **>>>setup.sh<<<**
> * **Another question**: Does your distro have **zenity** dependencie (packet) installed ????
>   because that `[x] Script Execution Aborted ..` normaly happens when users
>   forget to install **zenity** dependencie <-- ALL my bash tool's require zenity GUI's
>   to capture user inputs ....
>   
>   * check if you have zenity installed `zenity --version`
>   * install zenity `sudo apt-get install zenity`
>   * zenity homepage: https://help.gnome.org/users/zenity/
> 
> In version 1.0.15 release **@usama7628674** have help my config setup.sh to work in x64 bites:
> [#22 (comment)](https://github.com/r00t-3xp10it/venom/issues/22#issuecomment-381007778) Next time i will not respond you, since you dont know how to be polite ..and then you are going to be convinced that venom does not work in x64 and we all be happy ..

Thank you, sorry i was not trying to be rude or rude. Yes i did check both files, same error. Apt-get install Zenity solved it, and yes one can comment out the error message but it is not necessary. Say hi to Usama 4 me, 😉💯🔥, will post a video 4 other that might have the same problem, thank you-keep up the great work-ps sorry 4 being rude?
