### ISSUE TITLE
Option 8 - Agent 4 ( x86 bits restriction )

### ISSUE THREAD

**Issue by sgespinola** [r00t-3xp10it/venom#50]
This Module does not run under 32 bit (I'm trying do to this on a notebook 64 bit)

**Comment by r00t-3xp10it** [comment]
**'meterpeter'** project it only can be used under **'x64'** bits (attacker machine)
because Microsoft only have released **'powershell'** to x64 bits under linux distros ..
- [meterpeter home page](https://github.com/r00t-3xp10it/meterpeter)
- [Video meterpeter under Linux x64](https://www.youtube.com/watch?v=CmMbWmN246E)
- [Video meterpeter under Windows x64](https://www.youtube.com/watch?v=jRf7yFh47OA)
