### ISSUE TITLE
build 4 not compile python to exe

### ISSUE THREAD

**Issue by gearcapitan** [r00t-3xp10it/venom#7]
![kali linux-2017-04-07-19-57-44](https://cloud.githubusercontent.com/assets/13740942/24824175/85cba394-1bcc-11e7-8027-a8886bf73689.png)

**Comment by gearcapitan** [comment]
![sin titulo](https://cloud.githubusercontent.com/assets/13740942/24824380/ba890c54-1bcf-11e7-9147-8db6e70a4309.png)

**Comment by r00t-3xp10it** [comment]
<br />

Well i have just now try that build [**4 -> pyinstaller**]
and everything working fine on my side (**Linux kali rolling 32bits**)...

<br /><br />

**1º** - are you sure that you have paste corretlly the shellcode into **exec.py** template?
Dont you have pasted the 'semi-colon' [ **;** ] into [**rHfGjdSiJdK**] funtion?
![bug](http://2.1m.yt/fD0_jd6.png)

<br /><br />

**2º** - Maybee the error its on your **pyinstaller** install ..
because in my side it does not give that bug wile execution ..
![bug](http://4.1m.yt/CbgPb44.png)

<br /><br />

**3º** - **Payload.py** compiled to **payload.exe** And stored into **output** folder ..
![bug](http://2.1m.yt/PU6x0fS.png)

<br /><br />

4º - **Payload.exe** execution (and connection) using **wine** 
![bug](http://3.1m.yt/puqEFzC.png)

**Comment by gearcapitan** [comment]
how to fix pyinstaller ?

**Comment by gearcapitan** [comment]
When you tried to compile manually it gives me this error
![kali linux-2017-04-08-11-28-36](https://cloud.githubusercontent.com/assets/13740942/24830581/94e05ffa-1c4e-11e7-80e6-25bbcbe4df0e.png)

**Comment by gearcapitan** [comment]
When running ./setup, this happens
![kali linux-2017-04-08-11-37-36](https://cloud.githubusercontent.com/assets/13740942/24830644/d4d2cbba-1c4f-11e7-9852-13860c2906ff.png)

**Comment by r00t-3xp10it** [comment]
<br /> 

aaaaa like i've espected...
**pyinstaller was not completlly installed** ...
because it requires **pywin32** to work (32bits) <-- maybee there is a version to **64bits** too ..

    This appens because you are using a 64bits system, and when i wrote the tool
    i've used my system arch to build stuff (x86 = 32bites) ...

### How to fix the pyinstaller issue?
Dont ask me ..iam not the developer of pyinstaller or pywin ..
And i dont have a 64bits system were to try in fix the issue ...

**Comment by gearcapitan** [comment]
https://sourceforge.net/projects/pywin32/files/pywin32/Build%20220/

I managed to fix it, just download the specific pywin32 for the version of python 2.6 install it and that was it

**Comment by gearcapitan** [comment]
Forget what I said, if you compile but do not connect and check and it's not my network.

**Comment by r00t-3xp10it** [comment]
HINT: If you are in a 64bits system...
than wine command starts by wine64 <command>
and not by wine <command>

if you install stuff using wine command it will install soft in 'Program Files' (32bits)
insted of installing under 64 bits directorys 'Program Files (x64)' ..

**Comment by gearcapitan** [comment]
Already try to compile with win64 manually but it does not connect

**Comment by r00t-3xp10it** [comment]
**If the installation process informs you that Python is not found in the registry,
it almost certainly means you have downloaded the wrong version
either for the wrong version of Python, or the wrong "bittedness".**
