### ISSUE TITLE
Social Engineering - Fake PDF Trojan Horse

### ISSUE THREAD

**Issue by codings9** [r00t-3xp10it/venom#78]
Windows systems (vista|7|8|8.1|10)

8 (Amsi Evasion) |  Agent nº5

Version v1.0.17 Changelog

Hey, i was about to do a video for LBRY on Fake PDF Trojan Horse, and i ran upon this hiccup.
Let me know what steps i can take to fix this or help you fix it, thank you!
![Fake PDF Trojan Horse](https://user-images.githubusercontent.com/6113072/94765366-fdd05f00-035f-11eb-8bf2-79d6733c98f9.png)

**Comment by r00t-3xp10it** [comment]
Something its wrong then ..
because **`Client.exe`** its the same implant that both of us have been working on ..
Gist: https://gist.github.com/r00t-3xp10it/13e1bd5c657a1bd38bdf0a82d0e63309#gistcomment-3153563
.
1º - So review the **`Wine32`** settings (multi-arch support)...
   More info about the module can be found [**Here**](https://github.com/r00t-3xp10it/venom/wiki/Venom---Amsi-Evasion---agent-n%C2%BA5-(PDF-Trojan))<br />

2º - Or review the lib used to compile the Client.exe
**`i586-mingw32msvc-gcc (32bits)`** OR **`i686-w64-mingw32-gcc (64bits)`**
.
Review venom.sh settings:
https://github.com/r00t-3xp10it/venom/wiki/Venom---Amsi-Evasion---agent-n%C2%BA5-(PDF-Trojan)#final-notes

**Comment by r00t-3xp10it** [comment]
### Target machine (windows 10 - x64bit)
![test](https://user-images.githubusercontent.com/23490060/94939950-c205d880-04ca-11eb-8274-42440dfc256f.png)

### Attacker machine (Linux Kali - x32bit)

**Comment by codings9** [comment]
> Something its wrong then ..
> because **`Client.exe`** (Agent) its the same implant that both of us have been working on ..
> Gist: https://gist.github.com/r00t-3xp10it/13e1bd5c657a1bd38bdf0a82d0e63309#gistcomment-3153563
> 
> ### step by step
> 1º - does dropper.exe as is icon changed from exe to pdf icon ?
YES.
> 2º - does dropper.exe downloads/executes the pdf document ?
YES.
> 3º - does dropper.exe downloads/executes the Client.exe ?
YES.
> 4º - does venom listenner recive the connection from Client.exe ?
NO.
> No connection, from Linux side, tested on x86 (xterm opens and shuts down) and x64 same picture i posted earlier, even put this on Parrot OS, nothing.

**>>I did notice that you are using: Sign Executable for AV Evasion (Carbon Copy)
>>Dropper Certificate: www.microsoft.com
>>Client Certificate: www.microsoft.com**
That is the only difference i can see.  


> ### review
> 1º - So review the **`Wine32`** settings (multi-arch support)...
> More info about the module can be found [**Here**](https://github.com/r00t-3xp10it/venom/wiki/Venom---Amsi-Evasion---agent-n%C2%BA5-(PDF-Trojan))
> 
> 2º - Or review the lib used by venom.sh to compile the **dropper.exe**
> **`i586-mingw32msvc-gcc (32bits)`** OR **`i686-w64-mingw32-gcc (64bits)`**
> [Review the venom.sh -> 3 settings under your arch:](https://github.com/r00t-3xp10it/venom/wiki/Venom---Amsi-Evasion---agent-n%C2%BA5-(PDF-Trojan)#final-notes)
> 
> 3º - OR maybee x64 bits arch **compiled payload** (agent) its giving an error under target x64 bits...
> [Try to change venom.sh configs from x64 to x32 bits -> and build/test the agent then](https://github.com/r00t-3xp10it/venom/wiki/Venom---Amsi-Evasion---agent-n%C2%BA5-(PDF-Trojan)#final-notes)
> 
> ### Target machine (windows 10 - x64bit)
> ![test](https://user-images.githubusercontent.com/23490060/94939950-c205d880-04ca-11eb-8274-42440dfc256f.png)
> 
> ### Attacker machine (Linux Kali - x32bit)
> ![test2](https://user-images.githubusercontent.com/23490060/94940191-1610bd00-04cb-11eb-896d-c01af95fbdd3.png)

**Comment by r00t-3xp10it** [comment]
its not because of this **I did notice that you are using: Sign Executable for AV Evasion (Carbon Copy)**   that it fails ...
lets chat here: https://gist.github.com/r00t-3xp10it/0f1f02058ee6107c91adbdfaf1bbda8d?fbclid=IwAR3vHPOCqoheBbKiz56NwcL_0l-4UkLVpmiixGYG9PG1dgJGayHYlYUvRzI

**Comment by r00t-3xp10it** [comment]
Lol, it's because I  updated my Kali, so winetricks dotnet45 is  generating errors per the microsoft side of things.
i upgraded my Kali, and now i am over here fighting with winetricks dotnet45🤣😂
![16B24E53-A877-4BA3-988B-56D7A43FAF07](https://user-images.githubusercontent.com/6113072/95152712-955bf600-0742-11eb-92e9-aa66157874d4.png)
![C45F1D5F-9C95-4114-B715-21CA7F4F8E73](https://user-images.githubusercontent.com/6113072/95152715-968d2300-0742-11eb-834c-fb569e06ee10.png)

**Comment by codings9** [comment]
Thank you, here is the video:
https://lbry.tv/@MunYa:d/Fake-PDF-Trojan-Horse:0?r=2Doo3VYrEzk9UmEw9kKFmbfEZtFZBjrx

Not messing with Youtube, and 3 strikes, lol, again thanks.

**Comment by r00t-3xp10it** [comment]
tell me .. why the dropper does not present the PDF icon ??
its because its inside the archive when you execute it ??
