### ISSUE TITLE
debian ?

### ISSUE THREAD

**Issue by EchoNine** [r00t-3xp10it/venom#9]
tried using venom on **debian testing** "wine 32",
had to tweak venom.sh script to accept **pyinstaller.3.2.1** which worked but keeps giving errors.

plus any workaround to use venom on "Debian" or is it a kali only thing?

thx in adv.

**Comment by ChaitanyaHaritash** [comment]
thanks for reporting .. can you explain problem you are facing along with the screenshot? would more convenient for us to help you out :)

**Comment by EchoNine** [comment]
after choosing option no.4 followed by the option "pyinstaller" i get this:
![selection_001](https://cloud.githubusercontent.com/assets/8757525/26747586/6e09d80c-47ff-11e7-8b9d-2707beef31a7.png)

also, got this at script startup though i`m using metasploit-framework the git version:
![selection_002](https://cloud.githubusercontent.com/assets/8757525/26747624/a55c8bb0-47ff-11e7-8bcd-3effc87b67d6.png)



again, all are on debian-testing.
thank you.

**Comment by ChaitanyaHaritash** [comment]
Have you ran setup.sh located in directory aux? It lets users to install all required dependencies for venom.. 
do let me know if you have wine installed.. 

/etc/init.d/metasploit is not an issue, actually.. during msf installation(graphical installation) msf usually asks to "install metasploit as service" followed by "service metasploit status" so that it could be kick start just after boot. 
As we've made it compatible to kali primarily. And since you might be using some pentesting distro(according to screenshot).. so bash shell fails to start/stop it. You can ignore it.

**Comment by EchoNine** [comment]
yep ran setup.sh everything was ok & yes .. wine 32bit is installed & working fine also tested pyinstaller & MinGW separately on wine to confirm its working .. but can`t figure out whats going wrong.

**Comment by ChaitanyaHaritash** [comment]
what DISTRO are you using..?
check this issue .. it should help you better .. 
[https://github.com/r00t-3xp10it/venom/issues/7](https://github.com/r00t-3xp10it/venom/issues/7)

**Comment by EchoNine** [comment]
Debian Testing

**Comment by EchoNine** [comment]
funny .. i just downloaded & tried venom v.1.0.12 and its working fine! something wrong here!

Debian Testing + pywin32 installed and working fine.

**Comment by r00t-3xp10it** [comment]
**i just downloaded & tried venom v.1.0.12** <-- thanks for this report ..

now iam current finishing another project,
but in 2 weeks tops i will return woking in venom new release ..
**maybee at that time with your help we can make this work in your distro** ..

**Comment by EchoNine** [comment]
thank you for your time & effort .. will be on a look out for you next proj.

cheers.

**Comment by r00t-3xp10it** [comment]
<br />

1 - my script as identified (**uname -m**) your system as **64 bits** ..
2 - so when its going to '**compile**' agents, it uses **64bits configurations** ..
(I belive thats the reason for this bug now, because 64bits supported was added in v1.0.13)


<br /><br />

## quick fix:

a) Edit **venom.sh** script
b) Change the values from lines **83** to **84** ..
![error](http://3.1m.yt/k20RywQ.png)

**By this ones (32bits)**
![error](http://4.1m.yt/PaONff.png)
c) save the script and run it again ..

<br />

**This configuration will force venom to use 32bits settings when compiling agents ..**

**Comment by EchoNine** [comment]
Debian-testing has stopped using  "i586-mingw32msvc-gcc" instead uses "i686-w64-mingw32-gcc" though ill give it a try & let you know.

**Comment by EchoNine** [comment]
just tried you suggestion & got an extra negative outcome. though the correct path for PyInstaller was found, it refuses to compile it to .exe plus "cp from /home/USER/$IPATH/output/dist not found or directory non existing!" pops up.

so in short, i`m left with a *.py & *.raw files with no *.exe
very frustrating ... i guess its better to suggest if i may that venom remains a "kali" only framework rather than entirely manipulating the script to fit debian or ubuntu .. etc.

thx in adv.

**Comment by r00t-3xp10it** [comment]
Dont say its only a **KALI** thing, because many people with diferent linux distros use it ..
**ubuntu, kali, parrot, mint** <-- venom was tested in this distros (team menbers)

### Lets try this last soluction:
lets look at venom command that compiles the agent...
1 - maybee its `su $user -c` thats giving the error under your distro ..
2 - also check if the paths to `python26 and pyinstaller-2.0` are correct ..

![fix](http://3.1m.yt/bZZMuOy.png)
**The command it can be found in line 1214**

**Comment by EchoNine** [comment]
Installed pywin32 and pyinstaller as user.
Wine owned by user.
Using PyInstaller-3.2.1 -->  path is at /opt/.

any hints or do you know anyone running the script on debian?

**Comment by EchoNine** [comment]
note: in v1.0.12 i tweaked pyinstaller like this:

"wine ~/.wine/drive_c/Python27/python.exe   /opt/PyInstaller-3.2.1/pyinstaller.py --noconsole --onefile $IPATH .....etc"

also python27 is installed.

**Comment by r00t-3xp10it** [comment]
1- if your wine its installed under username ..
Them **su $user -c** its needed ...
`check if user= stores the correct value`

2 - the problem its on python26 and pyinstaller-2.0 install paths ..
Them tweak v1.0.13 to use that configuration too
"wine ~/.wine/drive_c/Python27/python.exe /opt/PyInstaller-3.2.1/pyinstaller.py --noconsole --onefile $IPATH .....etc"

This should do the trick ..

**Comment by r00t-3xp10it** [comment]
<br />

### Note:

**If the installation process informs you that Python is not found in the registry,
it almost certainly means you have downloaded the wrong version
either for the wrong version of Python, or the wrong "bittedness".**
https://sourceforge.net/projects/pywin32/files/pywin32/Build%20220/

<br />

### 1º bug-fix

**venom v1.0.14** allows user to **manually** install another versions
of this 2 softwares and use the '**settings**' file to force main tool to use them ..
![bug-fix](http://i.cubeupload.com/o89XVJ.png)

<br />

### 2º bug-fix

**template.py** execution under windows systems fixed with the insertion of new windows **API imports**
![bug-fix](http://i.cubeupload.com/cRjtfC.png)

**Comment by EchoNine** [comment]
finally .. after inserting "1º bug-fix" everything worked fine.

**Comment by r00t-3xp10it** [comment]
iam sorry about that ..
but i was busy in other projects :+1:
